language: node_js
node_js:
  - "6.10"
  - "8"
  - "9"
install:
  - npm install -g codecov
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
